Написание тестов через расширение вне общих модулей #1057
silverbulleters/add pull request #1060
Opened 2022-10-03 12:16 UTC by Absolemus

Добавлена возможность загружать тесты из модуля объекта обработки

реализация  #1057

сделанные изменения

- Добавлена возможность загружать тесты из модуля объекта обработки
-

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2022-11-25 16:59 UTC, artbear requested changes
есть замечания.

2022-11-25 16:59 UTC, artbear commented on plugins/ЗагрузчикРасширения/ЗагрузчикРасширения.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
предлагаю откатить этот хмл-файл, т.к. меняется режим совместимости

а он важен для работы продукта в старых версиях или режимах совместимости

2022-11-25 16:59 UTC, artbear commented on plugins/ЗагрузчикРасширения/ЗагрузчикРасширения/Forms/Форма.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
и этот файл предлагаю откатить из-за увеличения версии платформы

2022-11-25 16:59 UTC, artbear commented on plugins/ЗагрузчикРасширения/ЗагрузчикРасширения/Forms/Форма/Ext/Form.xml
> +<Form xmlns="http://v8.1c.ru/8.3/xcf/logform" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:dcscor="http://v8.1c.ru/8.1
и этот файл предлагаю откатить из-за увеличения версии платформы

2022-12-25 16:20 UTC, Absolemus commented on plugins/ЗагрузчикРасширения/ЗагрузчикРасширения/Forms/Форма/Ext/Form.xml
> +<Form xmlns="http://v8.1c.ru/8.3/xcf/logform" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:dcscor="http://v8.1c.ru/8.1
Откатил

2023-01-21 12:59 UTC, artbear approved these changes

2023-01-21 12:59 UTC, merged

2023-01-21 12:59 UTC, artbear commented
@Absolemus Большущее спасибо!