Изменены значения по умолчанию для запуска из командной строки.
silverbulleters/add pull request #1090
Opened 2023-04-18 23:23 UTC by yukon39

реализация  #1089 

сделанные изменения:
Изменены значения по умолчанию для запуска из командной строки, а именно:
ВыполнитьСценарии=Истина  (было Ложь)
ЗавершитьРаботуСистемы= Истина (было Ложь)
ВыгружатьСтатусВыполненияСценариевВФайл=Истина (было Ложь)
ПутьКФайлуДляВыгрузкиСтатусаВыполненияСценариев="$workspaceRoot/build/buildstatus.log" (было "")

Изменения позволяют запускать тестирование продукта без указания файла параметров с корректными значениями параметров для работы vanessa-runner.

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2023-04-26 18:11 UTC, artbear requested changes
Хороший ПР, но есть небольшое замечание

2023-04-26 18:11 UTC, artbear commented on plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
> +		КонтекстЯдра.СделатьСообщение("Не заполнен параметр: VBParams. Используются значения параметров по умолчению для запуска в режиме комаднйо строки.");
опечатка комаднйо

2023-04-26 18:11 UTC, artbear commented on plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
> +		КонтекстЯдра.СделатьСообщение("Не заполнен параметр: VBParams. Используются значения параметров по умолчению для запуска в режиме комаднйо строки.");
и все-таки лучше расшифровать, что за параметр VBParams, как было ранее - Не найден путь к JSON-файлу настроек

2023-04-27 11:33 UTC, yukon39 commented on plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
> +		КонтекстЯдра.СделатьСообщение("Не заполнен параметр: VBParams. Используются значения параметров по умолчению для запуска в режиме комаднйо строки.");
Исправлено

2023-04-27 12:13 UTC, merged