Переходить к следующей таблице, если из этой нового окна нету
silverbulleters/add pull request #1098
Opened 2023-04-28 08:30 UTC by BarinovIN

реализация  #1093

сделанные изменения

- Вместо установки результата, который больше не используется, переходить к следующей таблице, когда из текущей таблицы другая форма не открыта.

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2023-07-16 15:06 UTC, artbear requested changes

2023-07-16 15:06 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +			Продолжить;
вот с этой правкой не согласен. 

перед этим выполняется клик в таблице формы или заканчивается редактирование строки

оба этих действия могут вызывать ошибки или модальные окна, кажется, что нельзя пропускать последующие действия, т.е. нельзя делать Продолжить.

@BarinovIN что скажешь?

2023-08-30 09:52 UTC, BarinovIN commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +			Продолжить;
Действительно окончание редактирования строки так могло остаться непроверенным.
- Убрал `Продолжить`.
- Добавил проверку, что новое окно открыто перед проверкой интерфейса нового окна

2024-11-24 09:09 UTC, merged

2024-11-24 09:11 UTC, artbear commented
@BarinovIN Большое спасибо за доработку! Поздравляю вас с первым ПР в Ванесса-АДД

@vanessa-opensource/Collaborators - в полку контрибьюторов прибыло! 🥳