Критичность тестов
silverbulleters/add pull request #473
Opened 2019-04-30 09:17 UTC by theshadowco

Добавил возможность устанавливать метки критичности тестов для отчетов allure и allure v2.
При загрузке файла с тестом загрузчик вызывает процедуру установки уровня критичности теста.
Тест дергает сеттер загрузчика с параметром критичности теста.
Всего доступно 5 уровней критичности (blocker,critical,normal,minor,trivial).
По умолчанию устанавливается normal.

@silverbulleters/Collaborators - просьба прокомментировать и проверить

2019-04-30 14:31 UTC, artbear commented
@theshadowco хорошее дополнение для аллюр.

одно меня тревожит - сейчас уровень критичности выставляется не для одного мелкого теста, а для всех тестов, которые находятся в текущем наборе (внешней обработке с тестами).

т.е. получается, что нельзя установить разную критичность для разных тестов внутри одного набора (обработки с тестами).

предлагаешь так и оставить?
или все-таки дадим возможность управлять критичностью для каждого мелкого теста?

2019-05-02 14:41 UTC, theshadowco commented
Пока не было такой потребности (ни у разрабов, ни у тестеров).

Думаю, если появится реальная потребнсть - доработаем.

С уважением,
Максимов Валерий.
maximovvalery@gmail.com


вт, 30 апр. 2019 г. в 17:31, Artur Ayukhanov <notifications@github.com>:

> @theshadowco <https://github.com/theshadowco> хорошее дополнение для
> аллюр.
>
> одно меня тревожит - сейчас уровень критичности выставляется не для одного
> мелкого теста, а для всех тестов, которые находятся в текущем наборе
> (внешней обработке с тестами).
>
> т.е. получается, что нельзя установить разную критичность для разных
> тестов внутри одного набора (обработки с тестами).
>
> предлагаешь так и оставить?
> или все-таки дадим возможность управлять критичностью для каждого мелкого
> теста?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/silverbulleters/add/pull/473#issuecomment-487975587>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACJFXM3NZMJK7GAIZ7CUETTPTBJ5BANCNFSM4HJJ2GLQ>
> .
>

2019-05-06 06:49 UTC, theshadowco commented
@artbear 
Конфликты разрешили

2019-05-13 10:47 UTC, theshadowco commented
@artbear 
up

2019-05-14 12:06 UTC, artbear requested changes
Был в отпуске, руки не дошли. 
Вернулся.

есть небольшой вопрос с лишним файлом.

2019-05-14 12:06 UTC, artbear commented on F.A.Q.MD.orig
> +# FAQ
@theshadowco копии (.orig) не нужны. удалите их, пожалуйста!

2019-05-14 13:31 UTC, theshadowco commented on F.A.Q.MD.orig
> +# FAQ
упс :(

2019-05-14 13:41 UTC, theshadowco commented on F.A.Q.MD.orig
> +# FAQ
Поправил

2019-05-15 09:07 UTC, artbear commented
@theshadowco упали тесты по таймауту в упр.приложении
```
[Pipeline] { (TDD Тестирование)
[Pipeline] timeout
Timeout set to expire in 25 минут
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] bat
23:12:30  
23:12:30  c:\j\workspace\Vanessa.ADD_Fast_CI_PR-473>chcp 65001 
23:12:30  Active code page: 65001
23:12:30  
23:12:30  c:\j\workspace\Vanessa.ADD_Fast_CI_PR-473>vrunner xunit tests/xunit --settings tools/JSON/vrunner.json --reportsxunit "ГенераторОтчетаJUnitXML{build/junit-tdd/junit-tdd.xml};ГенераторОтчетаAllureXMLВерсия2{build/allure-tdd/allure.xml}"  
23:12:31  vanessa-runner v1.6.0
23:12:31  ИНФОРМАЦИЯ - Выполняю тесты  с помощью фреймворка ADD - c:\j\workspace\Vanessa.ADD_Fast_CI_PR-473\tests\xunit
23:12:31  ИНФОРМАЦИЯ - Выполняю команду/действие в режиме 1С:Предприятие
23:13:03  ИНФОРМАЦИЯ - .  ==>> набор тестов xunit
23:13:03  ИНФОРМАЦИЯ - .  ==>> набор тестов Тесты_ГенераторОтчетаJUnitXML_TFS
23:13:03  ИНФОРМАЦИЯ - .    -->> тест ТестДолжен_СоздатьОтчет

//// ВОТ ЗДЕСЬ ВИДНО ПАДЕНИЕ 

Cancelling nested steps due to timeout
23:37:26  Sending interrupt signal to process
23:37:36  After 10s process did not stop
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
```

2019-05-15 09:08 UTC, artbear commented
@theshadowco и также дымовые упали

Проверь, пожалуйста. что-то не так.

```
[Pipeline] { (Дымовое тестирование)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] timeout
22:45:58  Timeout set to expire in 25 минут
[Pipeline] {
[Pipeline] bat
22:46:00  
22:46:00  c:\j\workspace\Vanessa.ADD_Fast_CI_PR-473>chcp 65001 
22:46:00  Active code page: 65001
22:46:00  
22:46:00  c:\j\workspace\Vanessa.ADD_Fast_CI_PR-473>vrunner xunit tests/smoke --settings tools/JSON/vrunner.json --reportsxunit "ГенераторОтчетаJUnitXML{build/junit-smoke/junit.xml};ГенераторОтчетаAllureXMLВерсия2{build/allure/allure.xml}"  
22:46:00  vanessa-runner v1.6.0
22:46:01  ИНФОРМАЦИЯ - Выполняю тесты  с помощью фреймворка ADD - c:\j\workspace\Vanessa.ADD_Fast_CI_PR-473\tests\smoke
22:46:01  ИНФОРМАЦИЯ - Выполняю команду/действие в режиме 1С:Предприятие
22:46:20  ИНФОРМАЦИЯ - .  ==>> набор тестов smoke
22:46:20  ИНФОРМАЦИЯ - .  ==>> набор тестов ПроверкаРежимаБлокировки
22:46:20  ИНФОРМАЦИЯ - .  ==>> набор тестов Проверка режима блокировки данных РегистрНакопления
22:46:20  ИНФОРМАЦИЯ - .    -->> тест РегистрНакопления.РегистрНакопления2
23:10:58  Cancelling nested steps due to timeout
23:10:58  Sending interrupt signal to process
23:10:58  script returned exit code -1
[Pipeline] }
[Pipeline] // timeout
```

2019-05-15 09:10 UTC, artbear commented
а в обычном приложении ошибок нет.

2019-05-15 13:14 UTC, artbear commented
Если бы не падало, я бы в релиз 6.0.0 включил :(

но не судьба.

Жду исправление и буду включать в релиз 6.1.0 - через одну или 2 недели

2019-05-21 10:44 UTC, artbear commented
@theshadowco Что скажешь?

2019-05-21 12:45 UTC, theshadowco commented
@artbear 
Перепроверим на последнем релизе

2019-05-22 11:12 UTC, jmpjck commented
Слежу

2019-05-24 11:40 UTC, artbear commented
@theshadowco @jmpjck Удалось разрулить проблему?

2019-05-24 15:24 UTC, theshadowco commented
@artbear 
Да, тестируем, пришлем на сл неделе

2019-05-27 07:40 UTC, theshadowco commented
@artbear 
Поправили: 

> Исправил падение при потоковом формировании отчетов

2020-02-26 08:33 UTC, pumbaEO approved these changes

2020-11-07 17:19 UTC, closed without merging