Исправление ошибки доступа к файлу макета в клиент-серверном режиме
silverbulleters/add pull request #479
Opened 2019-05-07 12:41 UTC by ripreal

реализация  #Issue-478

сделанные изменения
- В методе ПолучитьТабличныйДокументTestClient() переделал использование абсолютных путей к временному файлу макета на относительные

@silverbulleters/Collaborators - просьба прокомментировать и проверить

2019-05-14 11:08 UTC, artbear requested changes

2019-05-14 11:08 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
@ripreal Метод `ПутьФайлаИлиДвоичныеДанныеДляСервера` как раз и предназначен для упрощения и ускорения работы в файловом/клиент-серверном режиме.

зря ты от него избавился.

фишка метода в том, что для файловой ИБ или если клиент/сервер на одной машине нет совершенно ненужной передачи макета в виде двоичных данных.

Возможно, проблема в реализации или использовании этого метода.

2019-05-14 11:09 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
точнее, их 2 парных метода
- один вызывается на клиенте
- другой вызывается на сервере

оба инкапсулируют и ускоряют переданных данных с файла на сервер.

2019-05-16 06:55 UTC, ripreal commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
@artbear В наше время с гигабитными скоростями оптимизация клиент-серверного взаимодействия не особо решает, я считаю.

Кроме того,  в текущем виде в мастере - этот кусок кода гарантировано приводит к ошибкам, если сервер и клиент на одной машине, но запущены под разными пользователями. 

Если считаешь критичным, то как мне ее по-другому можно исправить?

2019-05-21 10:46 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
@ripreal да, баг есть.

На Пульском хакатоне у коллег возник при попытке загрузки на мастер-классе по тестированию.

я подумаю, что не так. день или два, лады?
и либо приму твой ПР, либо придумаю другой обход

2019-05-21 10:47 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
> если сервер и клиент на одной машине, но запущены под разными пользователями.

@ripreal интересный кейс.
Неужели он часто встречается?

2019-05-21 12:38 UTC, ripreal commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
@artbear Да, у нас это основной сценарий для автоматического CI:
- есть проектный сервер, на котором стоят MS SQL, 1C сервер, jenkins-нода
- На этом проектном сервере запускается ADD тестирование под доменным пользователем 
jenkins
- А сам сервер 1С запущен под другим пользователем USR1CV8

2019-05-27 13:02 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> -				ПутьМакетаИлиДвоичныеДанные = ПутьФайлаИлиДвоичныеДанныеДляСервера(ИмяВременногоФайла);
@ripreal Нужно сделать передачу в командной строке и файл настройки 
для Объект.ИспользоватьПрямыеПути

по умолчанию оставить так, как сейчас
но в json-файле можно было настроить этот параметр и использовать в кейсах, аналогичных вашим.

2019-11-18 12:23 UTC, artbear commented
закрываю PR - т.к. довольно редкий кейс использования, а сам ПР поломает существующий функционал.

2019-11-18 12:23 UTC, closed without merging