WIP: Feature/issue 654
silverbulleters/add pull request #646
Opened 2020-01-13 08:06 UTC by TheDemonCat

Поддержка исключений для тестов ПроверкаРежимаБлокировки и ПроверкаЧтенияНеАдминистраторами

2020-01-15 08:53 UTC, TheDemonCat commented
@artbear Посмотришь PR?

2020-01-30 14:45 UTC, artbear requested changes
есть вопросы. ответишь или исправишь?

2020-01-30 14:45 UTC, artbear commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
Выгрузи исходники в 8.3.10, чтобы версия исходников была 2.4, а не 2.9

2020-01-30 14:45 UTC, artbear commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
Инициализация плагина настроек вроде бы лишняя.

даже на сервере.

Или я ошибаюсь?

2020-01-30 14:45 UTC, artbear commented on tests/smoke/ПроверкаЧтенияНеАдминистраторами/ПроверкаЧтенияНеАдминистраторами/Ext/ObjectModule.bsl
>  	ПлагинНастроек.Инициализация(КонтекстЯдра);
и здесь Инициализация плагина настроек вроде бы лишняя.

даже на сервере.

Или я ошибаюсь?

2020-01-30 14:45 UTC, artbear commented on tests/smoke/ПроверкаЧтенияНеАдминистраторами/ПроверкаЧтенияНеАдминистраторами/Ext/ObjectModule.bsl
> +		ЗаписьЖурналаРегистрации("ПроверкаЧтенияНеАдминистраторами",УровеньЖурналаРегистрации.Предупреждение,,,Сообщение);
предлагаю такое сообщение выдавать в общий лог через `КонтекстЯдра.ВывестиСообщение(Сообщение);`

иначе можем не увидеть на Jenkins и соответственно не исправить.

2020-01-30 14:45 UTC, artbear commented on tests/smoke/readme.md
> +"SmokeNonAdminReading" :{
Можешь заодно исправить пример json-файла в каталоге tests/smoke ?

2020-01-31 04:34 UTC, TheDemonCat commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
если ее не будет, настройки не определяются. проверено

2020-01-31 04:35 UTC, TheDemonCat commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
Выгрузить не смогу, у меня линукс и не хочется гемороиться с переустановкой, но ручками верну на 2.9

2020-01-31 04:35 UTC, TheDemonCat commented on tests/smoke/ПроверкаЧтенияНеАдминистраторами/ПроверкаЧтенияНеАдминистраторами/Ext/ObjectModule.bsl
> +		ЗаписьЖурналаРегистрации("ПроверкаЧтенияНеАдминистраторами",УровеньЖурналаРегистрации.Предупреждение,,,Сообщение);
принято

2020-01-31 04:36 UTC, TheDemonCat commented on tests/smoke/readme.md
> +"SmokeNonAdminReading" :{
да, думаю ты прав. Я про него что то не подумал

2020-01-31 04:36 UTC, TheDemonCat commented
@artbear Постараюсь все исправить на неделе

2020-02-10 06:35 UTC, TheDemonCat commented on tests/smoke/ПроверкаЧтенияНеАдминистраторами/ПроверкаЧтенияНеАдминистраторами/Ext/ObjectModule.bsl
>  	ПлагинНастроек.Инициализация(КонтекстЯдра);
@artbear тут тоже(

2020-02-10 06:35 UTC, TheDemonCat commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
@EvilBeaver ответишь? Тут убрать нельзя инициализацию

2020-02-10 06:37 UTC, TheDemonCat commented on tests/smoke/readme.md
> +"SmokeNonAdminReading" :{
https://github.com/silverbulleters/add/pull/646/commits/cdad8923d556b47472718e66086f2194932245ab

2020-02-10 06:38 UTC, TheDemonCat commented on tests/smoke/ПроверкаЧтенияНеАдминистраторами/ПроверкаЧтенияНеАдминистраторами/Ext/ObjectModule.bsl
> +		ЗаписьЖурналаРегистрации("ПроверкаЧтенияНеАдминистраторами",УровеньЖурналаРегистрации.Предупреждение,,,Сообщение);
добавил в двух тестах. Закрываем?

2020-02-14 16:18 UTC, artbear requested changes

2020-02-14 16:18 UTC, artbear commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
@TheDemonCat я недавно отвечал на похожую проблему. посмотри https://github.com/silverbulleters/add/issues/661

указанный код плохо работает при запуске тестов в упр.приложении

2020-02-14 16:21 UTC, artbear commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
@TheDemonCat также посмотри код из https://github.com/silverbulleters/add/issues/656

2020-02-15 19:06 UTC, EvilBeaver commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
Я не понял, что именно надо ответить?

2020-02-16 01:25 UTC, TheDemonCat commented on tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
> +	ПлагинНастроек.Инициализация(КонтекстЯдраПараметр);
@EvilBeaver, извини, ошибся ником(

2020-10-17 12:42 UTC, artbear commented
в итоге реализовано немного другим способом.
см. #645

2020-10-17 12:42 UTC, closed without merging