fix: Поправил чтение макета JSON
silverbulleters/add pull request #766
Opened 2020-06-30 20:31 UTC by KrapivinAndrey

Но выглядит ужасно

#733

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить
@artbear

2020-07-02 12:28 UTC, artbear requested changes
есть замечания и предложения

2020-07-02 12:28 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	ПутьФайла = ПутьФайлаПоДвоичнымДаннымСервер(ДвоичныеДанныеИлиПутьФичи, "json", ИмяВременногоФайла);
имя метода ПолучитьТекстовыйДокументНаСервере не совсем соответствует содержанию метода

у тебя жестко завязан на формат json

предлагаю сделать 2й параметр как РасширениеФайла и в него передавать `json`

2020-07-02 12:28 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ЭтоФайлДжейсон(ДвоичныеДанныеИлиПутьФайла) Тогда
в `ДвоичныеДанныеИлиПутьФайла` может приехать и путь файла, и двоичные данные.

и проверка ЭтоФайлДжейсон(ДвоичныеДанныеИлиПутьФайла) c кодом приведения к строке `НРег(Прав(...` неверно будет работать для двоичных данных

2020-07-02 12:28 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ЭтоФайлДжейсон(ДвоичныеДанныеИлиПутьФайла) Тогда
предлагаю проверку `ЭтоФайлДжейсон(ДвоичныеДанныеИлиПутьФайла) ` выполнять для `ИмяФайла`, в нем точно путь к файлу.

2020-07-03 19:57 UTC, KrapivinAndrey commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	ПутьФайла = ПутьФайлаПоДвоичнымДаннымСервер(ДвоичныеДанныеИлиПутьФичи, "json", ИмяВременногоФайла);
Поправил.

2020-07-03 19:57 UTC, KrapivinAndrey commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ЭтоФайлДжейсон(ДвоичныеДанныеИлиПутьФайла) Тогда
поправил

2020-07-04 16:16 UTC, artbear reviewed
отступы выглядят странно

2020-07-04 16:16 UTC, artbear commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +													, РасширениеФайла
что-то с отступами совсем грустно. гитхаб так показывает или действительно куда-то строки поехали?

2020-07-04 17:45 UTC, KrapivinAndrey commented on epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +													, РасширениеФайла
Я понял. В базе для разработки забыл табы на пробелы поменять.

2020-07-06 09:41 UTC, artbear approved these changes

2020-07-06 09:41 UTC, merged

2020-07-06 09:41 UTC, artbear commented
@KrapivinAndrey Большое спасибо!