ВыполнитьКомандуОС*СВыводом в линуксе не получает вывод
silverbulleters/add pull request #789
Opened 2020-10-15 21:34 UTC by kuntashov

Исправлено: Метод ВыполнитьКомандуОСБезПоказаЧерногоОкнаСВыводом() в линуксе не получал вывод (stdout) выполненной команды и всегда возвращал пустую строку.

Closes #788

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-10-16 16:08 UTC, artbear commented
@kuntashov выгрузка нужно в 8.3.10, а не в 8.3.17
исправишь?

2020-10-16 16:10 UTC, artbear requested changes

2020-10-16 16:10 UTC, artbear commented on plugins/УправлениеПриложениями/УправлениеПриложениями/Ext/ObjectModule.bsl
> +		ЗапуститьПриложение(ВремКоманда,, ЖдатьОкончания, КодВозврата);
наверное, здесь лучше добавить попытка-исключение удаление файла, вызвать исключение

и удаление файла делать после КонецПопытки

2020-10-16 16:10 UTC, artbear commented on plugins/УправлениеПриложениями/УправлениеПриложениями/Ext/ObjectModule.bsl
> +		УдалитьВременныйФайл(ИмяФайлаВывода);
ну и в этом блоке кода сделать Попытка - вызов приложения - Исключение удаление файла, вызов исключения

и еще одно удаление делать после КонецПопытки

2020-10-16 16:53 UTC, kuntashov commented
> @kuntashov выгрузка нужно в 8.3.10, а не в 8.3.17
> исправишь?

Да, поставлю 8.3.10 и исправлю.

2020-10-16 20:28 UTC, kuntashov commented on plugins/УправлениеПриложениями/УправлениеПриложениями/Ext/ObjectModule.bsl
> +		УдалитьВременныйФайл(ИмяФайлаВывода);
Исправил в https://github.com/vanessa-opensource/add/pull/789/commits/7b4a71af50e74ed3eccf97c7bffd377d125f75a6

2020-10-17 10:58 UTC, artbear commented on plugins/УправлениеПриложениями/УправлениеПриложениями/Ext/ObjectModule.bsl
> +				КонсольныйВывод = ПрочитатьФайлКакТекст(ИмяФайлаВывода, ИспользоватьКодировкуТекстаUTF8);
Увидел странную вещь
- консольный вывод возвращается только в случае кода возврата = 0 (
- т.е. если есть ошибки в приложении, код клиента консольный вывод не увидит и не поймет, в чем проблема (

@kuntashov к твоему ПР это но относится, конечно, но предлагаю убрать это условие.
и здесь, и в коде нашего 1С-приложения.

- и в модуле объекта, и в модуле формы, конечно.

что скажешь?

2020-10-17 10:59 UTC, artbear approved these changes

2020-10-26 17:58 UTC, merged

2020-10-26 18:00 UTC, kuntashov commented on plugins/УправлениеПриложениями/УправлениеПриложениями/Ext/ObjectModule.bsl
> +				КонсольныйВывод = ПрочитатьФайлКакТекст(ИмяФайлаВывода, ИспользоватьКодировкуТекстаUTF8);
В случае ошибок они обычно в консоли в stderr летят и перенаправлением `>` не ловятся, по крайней мере в линуксе нужно перенаправлять ошибки в stderr, на память как-то так : `&2>1`.

Но нужно ли это? Раз до сих пор не было сделано, значит не был кейсов использования. Имхо, как появятся - тогда и прикрутим, а сейчас мы умозрительно придумываем решение к задаче/потребности, которой пока нет.