TDD Плагин "Настройки" Метод ЕстьНастройка работает не в соответствии со своим описанием. Альтернативный метод ЕстьЗначениеНастройки.
silverbulleters/add pull request #801
Opened 2020-10-27 18:06 UTC by petypen

реализация  issue #793

сделанные изменения

- изменено описание метода `ЕстьНастройки` в соответствии с его поведением
- добавлен альтернативный метод `ЕстьЗначениеНастройки` Теперь можно проверить наличие настройки по пути из ключей и получить значение этой настройки.

> // Получает значение настройки по указанному имени или пути, а также проверяет,
> // имеется ли настройка по указанному пути.
> //
> // Параметры:
> //  ПутьНастроек		 - Строка	 - Путь из ключей настройки разделенных точкой,
> //    Например: "Ключ2.Ключ21"
> //  ЗначениеНастройки	 - 	Произвольный - найденное значение настройки, если ключа
> //    или пути из ключей нет в настройках, то возвращается Неопределено.
> // 
> // Возвращаемое значение:
> //  Булево - признак того, что настройка найдена

- Добавлены тесты для методов `ЕстьНастройка `и `ЕстьЗначениеНастройки`
- Добавлено описание методов в документацию плагина "Настройки"

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-10-28 18:31 UTC, artbear requested changes
Отличные изменения, пусть и смешанные от 2х разных ПР.

круто, даже с тестами )

переделай мои замечания и я смержу твой ПР

2020-10-28 18:31 UTC, artbear commented on plugins/Настройки/Настройки/Ext/ObjectModule.bsl
> -	ПоказатьСвойстваВРежимеОтладки(ИсточникНастроек);
зря убрал отладочные сообщения.
при ошибках отладочные сообщения помогают.
предлагаю вернуть эти 2 строки.

2020-10-28 18:31 UTC, artbear commented on tests/xunit/Plugins/Тесты_Настройки/Тесты_Настройки/Forms/Форма/Ext/Form/Module.bsl
> +// Не проходной тест. Должен упасть
1 название "не проходной тест" не очень понятен.
предлагаю заменить эту строку на "Падающий тест" вместо "Не проходной тест. Должен упасть"

во всех местах кода

2 подскажи, зачем нам падающий тест?
ты понимаешь, что этот тест будет падать и все CI будут падать.

если ты хочешь сделать негативный\отрицательный тест, тогда
- он не должен падать, а должен выполняться, как и любой правильный тест
- такой тест должен проверять, что появляется неверные\неправильные значения

например, часть кода ниже может быть такой
```bsl
Ожидаем.Что(бЕстьНастройка, 
	."Ожидали, что для ключа Ключ1.Ключ2.Ключ3 будет найдена настройка, но это не так!")
	.ЭтоЛожь();
```

2020-10-28 18:31 UTC, artbear commented on tests/xunit/Plugins/Тесты_Настройки/Тесты_Настройки/Forms/Форма/Ext/Form/Module.bsl
> +// Не проходной тест. Должен упасть
Предлагаю все такие падающие тесты переделать.

2020-10-29 15:54 UTC, petypen commented
@artbear Артур, учел рекомендации. Коммиты добавлены

2020-11-07 17:17 UTC, merged

2020-11-07 17:18 UTC, artbear commented
@petypen Большое спасибо!