Smoke тест программной записи элементов справочников
silverbulleters/add pull request #803
Opened 2020-10-28 23:18 UTC by AlexPCRus

реализация  #
тест программной записи элементов справочников реализован на базе теста проведения документов

сделанные изменения
- добавлены примеры настроек в smoke.bsp.json, smoke.example.json
- исходные файлы обработки помещены в каталог tests\smoke\тесты_ЗаписьЭлементовСправочников

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-10-29 22:28 UTC, artbear requested changes
Замечательный тест

Есть замечания
- одно критическое
- и 2 предложения

доработаешь?

2020-10-29 22:28 UTC, artbear commented on tests/smoke/тесты_ЗаписьЭлементовСправочников/тесты_ЗаписьЭлементовСправочников.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
у тебя выгрузка в 8.3.17
Перевыгрузи в 8.3.10 исходники, иначе не соберется.

2020-10-29 22:28 UTC, artbear commented on tests/smoke/тесты_ЗаписьЭлементовСправочников/тесты_ЗаписьЭлементовСправочников/Ext/ObjectModule.bsl
> +	"ВЫБРАТЬ ПЕРВЫЕ 1
у Справочников своя логика создания, с документами проще - бери последние и не ошибешься.
может быть, поделить выборку пополам
- половину первых брать
- половину последних
?

интересно? сделаешь?

2020-10-29 22:28 UTC, artbear commented on tests/smoke/тесты_ЗаписьЭлементовСправочников/тесты_ЗаписьЭлементовСправочников/Ext/ObjectModule.bsl
> +Процедура Тест_ЗаписатьЭлементСправочника(СправочникСсылка) Экспорт
а еще бы тест на запись групп для иерархических справочников добавить?

интересно? сделаешь?

2020-10-30 09:46 UTC, AlexPCRus commented on tests/smoke/тесты_ЗаписьЭлементовСправочников/тесты_ЗаписьЭлементовСправочников.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
готово

2020-10-30 09:46 UTC, AlexPCRus commented on tests/smoke/тесты_ЗаписьЭлементовСправочников/тесты_ЗаписьЭлементовСправочников/Ext/ObjectModule.bsl
> +	"ВЫБРАТЬ ПЕРВЫЕ 1
сделал. но не уверен что будут браться именно первые и последние элементы

2020-10-30 09:47 UTC, AlexPCRus commented on tests/smoke/тесты_ЗаписьЭлементовСправочников/тесты_ЗаписьЭлементовСправочников/Ext/ObjectModule.bsl
> +Процедура Тест_ЗаписатьЭлементСправочника(СправочникСсылка) Экспорт
может отдельно запилить? Или этот придется переименовывать.

2020-11-07 17:22 UTC, merged

2020-11-07 17:22 UTC, artbear commented
@AlexPCRus Спасибо!