fix ПроверкаМакетовСКД
silverbulleters/add pull request #806
Opened 2020-11-01 20:24 UTC by SidnevAV

сделанные изменения

- Оптимизация под тонкий клиент
- Рефакторинг

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-11-07 17:28 UTC, artbear requested changes
Есть достаточно критическое замечание.

и главный вопрос - зачем нужны эти правки, ведь тест макетов СКД прекрасно работает как серверный тест в тонком клиенте.
зачем тебе понадобилось делать текущую доработку?

2020-11-07 17:28 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД.xml
> +			<Name>Тесты_ПроверкаМакетовСКД</Name>
имя файла у тебя не изменилось, а внутреннее представление поменялось.
регистр первой буквы изменился.
предлагаю вернуть обратно, назвать с маленькой буквы.
соответствие имени важно для скриптов сборки\разборки внешних обработок.

2020-11-07 18:38 UTC, SidnevAV commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД.xml
> +			<Name>Тесты_ПроверкаМакетовСКД</Name>
Поправил

2020-11-07 18:41 UTC, SidnevAV commented
> Есть достаточно критическое замечание.
> 
> и главный вопрос - зачем нужны эти правки, ведь тест макетов СКД прекрасно работает как серверный тест в тонком клиенте.
> зачем тебе понадобилось делать текущую доработку?

@artbear 852 скд макета в конфе:
До оптимизации
![image](https://user-images.githubusercontent.com/56798144/98449071-b2208a80-2141-11eb-9429-1dfff3451410.png)
После:
![image](https://user-images.githubusercontent.com/56798144/98449084-c8c6e180-2141-11eb-8aa8-60b824a47d24.png)

Это с открытием и выполнением теста

2020-11-08 11:46 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД.xml
> +			<DefaultForm>ExternalDataProcessor.Тесты_ПроверкаМакетовСКД.Form.Форма</DefaultForm>
@SidnevAV еще здесь Заглавная буква осталась

2020-11-08 11:46 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД.xml
> +			<DefaultForm>ExternalDataProcessor.Тесты_ПроверкаМакетовСКД.Form.Форма</DefaultForm>
и еще в паре мест выше.

2020-11-08 11:48 UTC, artbear commented
По оптимизации понял, да, серьезное отличие!

2020-11-08 11:51 UTC, SidnevAV commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД.xml
> +			<DefaultForm>ExternalDataProcessor.Тесты_ПроверкаМакетовСКД.Form.Форма</DefaultForm>
поправил, вроде везде

2020-11-08 14:00 UTC, merged

2020-11-08 14:00 UTC, artbear commented
@SidnevAV Замечательно! принято.