TDD дополнена и уточнена документация "Создание файлов-тестов"
silverbulleters/add pull request #813
Opened 2020-11-09 16:51 UTC by petypen

реализация  #

сделанные изменения

- изменен порядок глав, все примерв в конце
- новая глава Предопределенные свойства (переменные) теста
- дополнена глава API НаборТестов
- уточнен пример
- рефакторинг, ради единообразия текста

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-11-10 09:41 UTC, artbear commented
@petypen Как интересно!

сейчас посмотрю и отпишусь.

2020-11-10 09:46 UTC, artbear requested changes
Замечательные доработки текста.

предлагаю сделать небольшую правку и я готов замержить !

2020-11-10 09:46 UTC, artbear commented on doc/xdd/Создание-файлов-тестов.MD
> +	НаборТестов.НачатьГруппу("Группа тестов");
К сожалению, строка `КонтекстЯдра = КонтекстЯдраПараметр;` нужна (
метод Инициализация не всегда вызывается (

чтобы не ошибаться, я внутри ЗаполнитьНаборТестов всегда вызываю метод Инициализация 
и тесты прекрасно работают

предлагаю так в доке и указать.

2020-11-10 16:45 UTC, petypen commented
@artbear Артур, замечания по документации учтены

2020-11-15 12:30 UTC, merged

2020-11-15 12:30 UTC, artbear commented
@petypen Очередное огромное спасибо!