add Тесты_ПереходНаУправляемыеФормы
silverbulleters/add pull request #814
Opened 2020-11-12 21:21 UTC by SidnevAV

Новый тест: Тесты_ПереходНаУправляемыеФормы
- Тест проверяет, что все формы конфигурации управляемые.
- Полезен для перевода конфигурации на управляемые формы.

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-11-15 12:39 UTC, artbear requested changes
Хороший тест. у меня есть небольшие замечания.

2020-11-15 12:39 UTC, artbear commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +	Если ИсключенияИзПроверок.Получить(ВРег(ПолноеИмяМетаданных)) <> Неопределено
ИМХО вместо такого явного сравнения юзать бы метод Контекст.ЕстьВИсключаемойКоллекции или ЕстьВИсключаемойКоллекции.СтрокаСоответствуетШаблону

тогда бы исключения можно было расширить через шаблоны с * и неполный текст шаблона

2020-11-15 12:39 UTC, artbear commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +Функция ИмяСодержитПрефикс(Имя, Префикс)
для скорости я предлагаю передавать уже подготовленный Префикс - ВРег(Префикс)

вместо постоянного приведения к верхнему регистру фактически в цикле

2020-11-15 18:00 UTC, SidnevAV commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +	Если ИсключенияИзПроверок.Получить(ВРег(ПолноеИмяМетаданных)) <> Неопределено
Сейчас уже можно задавать исключение по всем объектам метаданных определенного типа, пример в настройках "Отчет.*".
Попробовал переделать на Контекст.ЕстьВИсключаемойКоллекции, на 4400 формах в конфигурации выполнение теста повисло на 20+ минут. Функционал с регулярными выражениями новый и не совсем оптимизированный.
Предлагаю оставить эту проверку как есть. Потом после оптимизации можно будет поправить.

2020-11-15 18:01 UTC, SidnevAV commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +Функция ИмяСодержитПрефикс(Имя, Префикс)
Убрал ВРег() и оптимизировал получение имени теста.

2020-11-16 14:34 UTC, artbear commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +	Если ИсключенияИзПроверок.Получить(ВРег(ПолноеИмяМетаданных)) <> Неопределено
Интересное замечание по производительности. сделаю отдельный ишуз на проверку

2020-11-16 15:31 UTC, artbear commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +	ВыполнятьТест = Истина;
может быть, для таких доп.тестов делать значение по умолчанию Ложь - т.е. тест будет выключен?

2020-11-16 15:39 UTC, artbear commented
@SidnevAV и здесь конфликт в tools/JSON/xUnitParams.json

2020-11-16 20:06 UTC, SidnevAV commented on tests/smoke/Тесты_ПереходНаУправляемыеФормы/Тесты_ПереходНаУправляемыеФормы/Forms/Форма/Ext/Form/Module.bsl
> +	ВыполнятьТест = Истина;
Поправил

2020-11-30 15:38 UTC, merged

2020-11-30 15:39 UTC, artbear commented
@SidnevAV очередное большое спасибо!