fix smoketest Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный
silverbulleters/add pull request #816
Opened 2020-11-15 20:16 UTC by SidnevAV

Исправления по тесту *Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный*

сделанные изменения:

1. Оптимизация работы теста
2. Добавлены новые настройки:
      -  "Используется": true,
      -  "ВыводитьИсключения": true,
      -  "ПропускатьОбъектыСПрефиксомУдалить": false,
      -   "ОпределяемыйТипКомментарий": Имя определяемого типа "Комментарий" для проверки типа реквизита "Комментарий" документов,
      -  "ОпределяемыйТипОтветственный": Имя определяемого типа "Ответственный" для проверки типа реквизита "Ответственный" документов,

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-11-16 15:36 UTC, artbear commented
@SidnevAV я вмержил твои предыдущие ПР, и теперь конфликты в файле tools/JSON/xUnitParams.json

поправь их.

2020-11-16 15:38 UTC, artbear requested changes
есть предложения

2020-11-16 15:38 UTC, artbear commented on tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
>  	ВыполнятьТест = Истина;
вот этот тест почти наверняка нужно делать необязательным по умолчанию, чтобы уменьшить лишние ложные срабатывания.

т.к. в большинстве типовых поля Комментарий и ответственный не являются обязательными.

2020-11-16 20:12 UTC, SidnevAV commented on tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
>  	ВыполнятьТест = Истина;
Поправил

2020-11-30 15:35 UTC, artbear requested changes
Предлагаю немного уточнить поведения для избежания ложных срабатываний.

2020-11-30 15:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
> +	КонецЕсли;
Предлагаю сразу пропускать тест, если у документа нет реквизита Комментарий 

сейчас, если я правильно понимаю, будет выдана ошибка, что неверно.

не во всех документах есть этот реквизит.

2020-11-30 15:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
> +	КонецЕсли;
аналогично пропускать по реквизиту Ответственный.

2020-11-30 15:40 UTC, artbear commented
смержил твой же соседний ПР https://github.com/vanessa-opensource/add/pull/814

и опять конфликты все в том же tools/JSON/xUnitParams.json

поправишь?

2020-11-30 19:05 UTC, SidnevAV commented on tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
> +	КонецЕсли;
готово

2020-11-30 19:05 UTC, SidnevAV commented on tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
> +	КонецЕсли;
готово

2020-12-07 15:45 UTC, merged