XDD Глобально доступный клиентский контекст для модульных тестов
silverbulleters/add pull request #820
Opened 2020-12-07 17:03 UTC by petypen

реализация  #818 
XDD Глобально доступный клиентский контекст для модульных тестов
сохранение и чтение глобального клиентского контекста

Реализована процедура, которая в браузере тестирования сохраняет пользовательский клиентский контекст. Значение контекста существует весь сеанс тестирования. Значение контекста хранится на клиенте и в отличии от контекста сохраненного методом `СохранитьКонтекст(Контекст)` не передается на сервер при выполнении внутренней логики браузера тестирования.

сделанные изменения

- Добавлен метод СохранитьГлобальныйКлиентскийКонтекст
- Добавлен метод ПолучитьГлобальныйКлиентскийКонтекст
- Добавлены тесты глобального клиентского контекста
- Добавлена документация глобального клиентского контекста

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2020-12-15 18:35 UTC, artbear commented
@petypen Интересная тема.

предлагаю наименование методов упростить до
- СохранитьГлобальныйКонтекст
- ПолучитьГлобальныйКонтекст
без использования Клиентский

2020-12-15 18:41 UTC, artbear commented
По опыту использования контекстов удобно не задавать их каждый раз через указанные методы, а сразу задавать коллекцию ключей-задачей в виде структуры (предпочтительно) или соответствия 

и использовать АПИ для управления или даже без АПИ, всегда зная, что такой Контекст - это структура

и юзать следующее АПИ контекста
- ГлобальныйКонтекст()
- ЗначениеИзГлобальногоКонтекста(Ключ)
- ДобавитьВГлобальныйКонтекст(Ключ, Значение)
- УдалитьИзГлобальногоКонтекста(Ключ)

2020-12-20 10:40 UTC, petypen commented
@artbear Артур, добрый день. Спасибо за дельные замечания.
Сделал PR с учетом предложенного API контекста.

-- доработан браузер тестирования
-- уточнена документация
-- уточнены тесты

2021-01-11 16:02 UTC, artbear requested changes
предлагаю немного доработать.

2021-01-11 16:02 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +#КонецОбласти
на последней строке лучше сделать перенос строки, тогда гит будет учитывать историю этой последней строки.

2021-01-11 16:02 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ТипЗнч(ГлобальныйКонтекст) <> Тип("Структура") Тогда
Предлагаю этот блок удалить

ведь глоб.контекст в любом случае уже должен быть инициализирован в новую структуру перед запуском тестов.

иначе наш тест не будет честным.

```bsl
	Если ТипЗнч(ГлобальныйКонтекст) <> Тип("Структура") Тогда
		ГлобальныйКонтекстИнициализировать();
	КонецЕсли;
```

2021-01-11 16:02 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ТипЗнч(ГлобальныйКонтекст) <> Тип("Структура") Тогда
и здесь удалить

2021-01-11 16:02 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ТипЗнч(ГлобальныйКонтекст) <> Тип("Структура") Тогда
и здесь удалить

2021-01-11 16:02 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Если ТипЗнч(ГлобальныйКонтекст) <> Тип("Структура") Тогда
Проверь, плиз, тест после этой правки.

может быть, первичная инициализация не в том месте выполняется?

2021-01-11 17:23 UTC, petypen commented
@artbear  Артур, учел замечания.

2021-02-26 19:44 UTC, artbear approved these changes
Отлично. @petypen Большое спасибо за терпение!
Делаю мерж.

2021-02-26 19:44 UTC, merged