Сделал группы элементов на основной форме сворачиваемыми
silverbulleters/add pull request #829
Opened 2021-01-01 14:38 UTC by sulfur17

реализация  #

сделанные изменения

-
-

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-01-11 15:46 UTC, artbear requested changes
есть вопросы.
обычная форма зачем менялась?

2021-01-11 15:46 UTC, artbear commented on plugins/СериализаторMXL/СериализаторMXL/Forms/Форма/Ext/Form/form
> +{6,3cd9c335-5e47-4e4c-8c2e-879549b54374,1,fbe38877-b914-4fd5-8540-07dde06ba2e1,
А что менялось в обычной форме?
довольно много изменений видно.

возможно, они фейковые, но это не очень понятно.

2021-01-11 15:46 UTC, artbear commented on plugins/СериализаторMXL/СериализаторMXL/Forms/Форма/Ext/Form/Module.bsl
> +	Отказ = (Вопрос("Вы действительно хотите закрыть обработку?", РежимДиалогаВопрос.ДаНет,,,"Подтвердите выход") = КодВозвратаДиалога.Нет);
есть стандарт у 1С - не устанавливать безусловно значение Отказ. а только в зависимости от условия устанавливать нужное значение.

чтобы не переписать значения от других подписчиков на событие.

в коде ничего страшного нет, конечно, но изменение обычной формы к этому ПР не относятся.

лучше бы их откатить.

2021-01-11 15:49 UTC, sulfur17 commented on plugins/СериализаторMXL/СериализаторMXL/Forms/Форма/Ext/Form/form
> +{6,3cd9c335-5e47-4e4c-8c2e-879549b54374,1,fbe38877-b914-4fd5-8540-07dde06ba2e1,
да, похоже они фейковые, я ее не менял

2021-01-11 15:52 UTC, sulfur17 commented on plugins/СериализаторMXL/СериализаторMXL/Forms/Форма/Ext/Form/Module.bsl
> +	Отказ = (Вопрос("Вы действительно хотите закрыть обработку?", РежимДиалогаВопрос.ДаНет,,,"Подтвердите выход") = КодВозвратаДиалога.Нет);
Не понимаю откуда взялось это изменение. Если я и менял обычную форму, то разве что по ошибке.
Как теперь лучше сделать? Мне самому откатить изменения?

2021-01-12 05:23 UTC, sulfur17 commented
@artbear я отменил все изменения обычной формы

2021-02-21 10:36 UTC, artbear approved these changes

2021-02-21 10:36 UTC, merged

2021-02-21 10:37 UTC, artbear commented
@sulfur17 Большое спасибо!