xddTestRunner fix ПодробноеПредставлениеОшибки
silverbulleters/add pull request #833
Opened 2021-01-04 17:45 UTC by SidnevAV

сделанные изменения:

- Исправлена проверка "ИспользуютсяСинхронныеВызовыРасширенийПлатформыИВнешнихКомпонент". Режим совместимости 8.3.14, включен синхронный вызов расширений платформы и внешних компонент, при старом варианте выполнение тестов зависало на неопределенное время.
- Добавлен параметр "ВыводитьПодробноеПредставлениеОшибки". Получение подробного представления ошибки сильно влияет на скорость выполнения тестов.
Выполнение одного теста с получением подробного представления ошибки:
![image](https://user-images.githubusercontent.com/56798144/103560802-76980780-4ec9-11eb-9859-5f6bce58c52b.png)
Выполнение того же теста с получением краткого представления ошибки:
![image](https://user-images.githubusercontent.com/56798144/103560775-68e28200-4ec9-11eb-99db-e873fbe42dd7.png)

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-01-11 15:32 UTC, artbear commented
>Добавлен параметр "ВыводитьПодробноеПредставлениеОшибки". Получение подробного представления ошибки сильно влияет на скорость выполнения тестов.

@SidnevAV очень интересно, я не думал, что настолько сильное влияние (

2021-01-11 15:36 UTC, artbear requested changes
Нужно исправление

2021-01-11 15:36 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	ВыводитьПодробноеПредставлениеОшибки = Истина;
вот здесь, похоже, должно быть `Объект.ВыводитьПодробноеПредставлениеОшибки = Истина;`

иначе эта настройка при интерактивном запуске всегда будет Ложь, т.к. условие ниже не выполнится (

2021-01-11 15:41 UTC, SidnevAV commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	ВыводитьПодробноеПредставлениеОшибки = Истина;
@artbear Исправлено.

2021-01-11 15:54 UTC, artbear approved these changes

2021-01-11 15:55 UTC, merged

2021-11-10 07:24 UTC, LazarenkoA commented
а добавьте описание этого параметра в документацию