Feature/issue 907
silverbulleters/add pull request #908
Opened 2021-10-06 12:56 UTC by maximsamokhval

реализация  #907 

сделанные изменения

- Добавлен пример создания собственного плагина
- Добавлена ссылка на пример создания плагина

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-10-07 16:53 UTC, artbear requested changes
Хорошая документация, но есть небольшие замечания!

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> + - Открыть в конфигураторе шаблон обработки - утилиты
Предлагаю указать относительный путь к этому шаблону

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +- Cохранить обработку с именем РаботаСМассивами.epf, в каталоге C:\Program Files\OneScript\lib\add\plugins
уточнить - 
>сохранить обработку с именем РаботаСМассивами.epf в каталоге установки Vanessa-ADD, например, `C:\Program Files\OneScript\lib\add\plugins`

а также можно штатно сохранить исходники нового плагина и опубликовать через механизм пул-реквестов согласно руководству контрибьютора Vanessa-ADD

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +  РаботаСМассивами = КонтекстЯдра.Плагин("РаботаСМассивами");
что-то с отступами

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Процедура Инициализация(КонтекстЯдраПараметр) Экспорт
у тебя пример плагина работает на клиенте, а в коде вызова не указана аннотация НаКлиенте

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Процедура ЗаполнитьНаборТестов(НаборТестов, КонтекстЯдраПараметр) Экспорт
и здесь нет НаКлиенте

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Функция ОписаниеПлагина(ВозможныеТипыПлагинов) Экспорт
в девелоп-версии плагина я добавил первый обязательный параметр КонтекстЯдра

и для серверных тестов и клиентских тестов

шаблоны я также поменял. Посмотри.

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Процедура ТестДолжен_ДобавитьЗначениеВМассив
не хватает скобок после имени метода

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +  Ожидаем.Что(МассивСоЗначением)
Ожидаем - неизвестная переменная.

Лучше явно создать эту переменную, как в шаблоне тестов

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Процедура Инициализация(КонтекстЯдраПараметр) Экспорт
хотя, похоже, что у тебя серверный тест, и тогда НаКлиенте не нужно.

предлагаю явно об этом написать - пример вызова плагина из серверного теста

2021-10-07 16:53 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> + - В модуле объекта в методе ОписаниеПлагина закомментировать исключение и добавить собственное представление плагина, например, "Работа с массивами"
не нужно комментировать исключение, его нужно удалять.

не оставляем ненужный код в комментариях, без жалости удаляем его.

2021-10-08 10:51 UTC, maximsamokhval commented on doc/xdd/Создание-плагина.MD
> +Функция ОписаниеПлагина(ВозможныеТипыПлагинов) Экспорт
Кстати, здесь у меня вопрос, для версии 6.6.5 - мой пример рабочий, и я по началу сделал для девелоп версии и он конечно не заработал. В документации описывать для какой из версий? Или сделать для обеих?

2021-10-08 11:05 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> + - Открыть в конфигураторе шаблон обработки - утилиты
указать /doc/PluginsTemplates/ШаблонУтилиты

важно указать первый слеш!

2021-10-08 11:06 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> + - Открыть в конфигураторе шаблон обработки - утилиты
или сразу корневой хмл-файл указать

2021-10-08 11:06 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> + - Открыть в конфигураторе шаблон обработки - утилиты
/doc/PluginsTemplates/ШаблонУтилиты/ШаблонУтилиты.xml

2021-10-10 18:33 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Функция ОписаниеПлагина(ВозможныеТипыПлагинов) Экспорт
Давай сразу для девелоп-версии, релиз я совсем уже скоро выпущу. в октябре точно.

2021-10-10 18:36 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +	    .Равно(1);
А можно вот так написать полностью в текучем стиле

```bsl
Ожидаем.Что(МассивСоЗначением)
  .ИмеетТип(Тип("Массив"))
  .ИмеетДлину(1);
```

2021-11-10 13:14 UTC, artbear commented
К сожалению, в релиз не попало (
будем исправлять в след.релизе

2021-11-15 13:01 UTC, artbear requested changes
лишний код жля тестов

2021-11-15 13:01 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +КонецФункции
этот метод в тесте не нужен

2021-11-15 13:01 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +Функция ОписаниеПлагинаНаСервере(Знач ВозможныеТипыПлагинов)
метод не нужен в тесте

2021-11-15 13:14 UTC, artbear commented on doc/xdd/Создание-плагина.MD
> +КонецФункции
этот метод и область для него также нужны.
удаляй и я замержу

2021-11-15 13:34 UTC, merged

2021-11-15 13:35 UTC, artbear commented
@maximsamokhval Очередное спасибо в твою сторону!