fix: Исправление метода ПодходящийРежимСовместимостиПлатформы, если у…
silverbulleters/add pull request #938
Opened 2021-11-11 11:14 UTC by maximsamokhval

Добавлена проверка в метод ПодходящийРежимСовместимостиПлатформы

реализация  #936 

сделанные изменения

- Добавлена проверка в метод ПодходящийРежимСовместимостиПлатформы
- Если установлен режим совместимости "Не использовать" или "DontUse" функция ПодходящийРежимСовместимостиПлатформы вернет истину, т.к имеет высший приоритет.

Ссылка на обсуждение https://t.me/vanessa_opensource_chat/3052 

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-13 13:51 UTC, artbear requested changes

2021-11-13 13:51 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
> +	КонецЕсли;
сейчас эта правка исправляет проблему точечно.

предлагаю эту проверку перенести в публичный метод ВерсияПриложенияБольшеИлиРавнаЧемЗаданная

тогда этот метод будет правильным всегда

2021-11-15 12:47 UTC, maximsamokhval commented on epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
> +	КонецЕсли;
@artbear перенес в метод ВерсияПриложенияБольшеИлиРавнаЧемЗаданная

2021-11-15 12:48 UTC, maximsamokhval commented
@artbear прошу проверить

2021-11-15 12:56 UTC, merged