исправлено #932
silverbulleters/add pull request #941
Opened 2021-11-13 14:09 UTC by LazarenkoA

реализация  #932 

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-13 14:22 UTC, artbear requested changes

2021-11-13 14:22 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	|", Сдвиг = 0) Экспорт
Давай будем аккуратно добавлять экспортные функции в ядро.

по возможности лучше публичные методы выносить в плагины, если эта функциональность будет еще кем-то юзаться.

Предлагаю перенести все публичные методы в плагин СтроковыеУтилиты
а здесь только переиспользовать.

2021-11-13 14:22 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +Функция ДополнитьСтроку(Знач Значение, Знач ДлинаСтроки, Знач Символ = "0", Знач Режим = "Слева") Экспорт
и этот метод

2021-11-13 14:22 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +Функция СформироватьСтрокуСимволов(Знач Символ, Знач ДлинаСтроки) Экспорт
и этот метод

2021-11-13 19:38 UTC, artbear requested changes
Есть предложения по исправлению.

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +//   -
Описание метода не по стандарту https://its.1c.ru/db/v8std#content:453:hdoc

исправь, пожалуйста.

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Forms/Форма/Ext/Form/Module.bsl
> +Функция КлючЗначениеВСтроку(КлючЗначение, Символ = "
и здесь описание не по стандарту

2021-11-13 19:38 UTC, artbear commented on epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +	Отладка("ИерархияИсполнения: " + СтроковыеУтилиты.КлючЗначениеВСтроку(ИерархияИсполнения));
название метода неинформативно.

Предлагаю наименование ПредставлениеКоллекции

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +
лишние пустые строки

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +	Для Каждого кз Из КлючЗначение Цикл
Предлагаю называть переменные по стандарту в КемелКейс-нотации

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +		врем = Новый Массив();
наименование сделай с заглавной буквы

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +		Для Каждого знч Из Значение Цикл
наименование сделай с заглавной буквы

2021-11-13 19:38 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +Функция ОбработкаТипа(Значение, Символ, Сдвиг)
название метода не говорит о назначении метода. лучше переназвать.

например, ПредставлениеЗначения

2021-11-14 14:49 UTC, LazarenkoA commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +	Для Каждого кз Из КлючЗначение Цикл
о чем речь, не понимаю, КлючЗначение и так в кемл нотации

2021-11-14 14:51 UTC, LazarenkoA commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +	Для Каждого кз Из КлючЗначение Цикл
Про кз? ну CamelCase для слова из 2х букв не подходит, тогда это upcase получится или просто с заглавной

2021-11-14 16:34 UTC, artbear requested changes
Модуль объекта не поменялся

2021-11-14 16:34 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +Функция КлючЗначениеВСтроку(КлючЗначение, Символ = "
осталось старое название

2021-11-14 16:34 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +	Для Каждого кз Из КлючЗначение Цикл
кз так и осталось.

2021-11-14 16:34 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +Функция ОбработкаТипа(Значение, Символ, Сдвиг)
странно, не изменилось.

2021-11-14 16:34 UTC, artbear commented on plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
> +//   -
в модуле объекта ничего не исправил, а замечания закрыл (

2021-11-14 17:18 UTC, artbear approved these changes

2021-11-14 17:18 UTC, merged