Переделка кода работы с модальными окнами
silverbulleters/add pull request #943
Opened 2021-11-13 18:37 UTC by LazarenkoA

Показания к переписыванию кода были в том, что очень много было ошибок по типу
![image](https://user-images.githubusercontent.com/15386101/141653731-4670504c-f655-4aec-8d5b-0628da3f7f69.png)
полез в код и понял, что алгоритм в целом не корректен (ниже пояснения).

В рамках этого ПР сделано:
 - расширено логирование.
 - внесена новая функция в тест `тесты_КомандныйИнтерфейс`, а именно возможность исключать конкретные "локальные" команды 
![image](https://user-images.githubusercontent.com/15386101/141653916-ef9016ba-6e07-4876-a6d4-4d2529028b92.png)
Это нужно что бы сузить исключения, например в целом справочник/документ исключать не хотелось бы, а вот одну команду (которая например открывает диалог работы с файлами) исключить нужно, раньше пришлось бы исключать весь справочник.
 - исправлены ошибки и попутно исправлена логика поиска и закрытия окон 
   - поправил #923
   - переписан этот странный алгоритм https://github.com/vanessa-opensource/add/blob/fabb5ee9b2fad861beac82741dce420a4e8dd639/plugins/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L923
   - сейчас реализовано так, если мы нашли правило по заголовку, то мы пытаемся закрыть это окно, без проверки полей этого окна. Вот пример https://github.com/vanessa-opensource/add/blob/fabb5ee9b2fad861beac82741dce420a4e8dd639/plugins/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L474 https://github.com/vanessa-opensource/add/blob/fabb5ee9b2fad861beac82741dce420a4e8dd639/plugins/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L475 сначала находится окно, причем без учета полей (в `ОкноПредупреждение` проверяются только заголовки) потом это окно пытается закрыться и там поля проверяются, но поля могут же быть от другого описания. т.е. в случае если я задам 2 описания, одно с заголовком "Окно1" и индексом кнопки 1 и второе правило с заголовком "Окно1" + поля "поле1" и индексом кнопки 2, работать будет не корректно т.к. в принципе по заголовку в соответствии будет или то или то описания (просто перетрется). Другой пример я задаю 2 описания "Окно1" и индексом кнопки 1 и второе правило с заголовком "Окно2" + поля "поле1" и индексом кнопки 2, так же работать будет не корректно т.к. в `ОкноПредупреждение` найдется Окно1 а в НажатьКнопкуМодальногоДиалога проверяется по общей коллекции полей, без привязки к конкретному описанию и если в Окно1  есть поле "поле1" найдется вторая кнопка, что не корректно. Я Сделал, что поиск окон происходит заголовок + поля по **И**. Если окно найдено по заголовку, далее описания отбирается по полям именно с таким заголовком, если полей нет, значит только по заголовку, если заголовка нет, только по полям.
   - унифицировал алгоритм поиска описания, а то сейчас в разных местах это происходит

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-13 19:41 UTC, artbear requested changes

2021-11-13 19:41 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
выгрузи исходники на платформе 8.3.10, а не 8.3.18 или соседней.

в проекте исходники в формате 8.3.10

2021-11-13 19:50 UTC, LazarenkoA commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
done

2021-11-13 19:58 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Templates/СкринОшибки_png.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
и здесь 2.10, а не 2.4

а вообще предлагаю удалить этот макет, т.к. для исполнения он не нужен, насколько я понял.

2021-11-13 19:59 UTC, artbear commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Templates/СкринОшибки_png.xml
> +<MetaDataObject xmlns="http://v8.1c.ru/8.3/MDClasses" xmlns:app="http://v8.1c.ru/8.2/managed-application/core" xmlns:cfg="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:cmi="http://v8.1c.r
и здесь 2.10, а не 2.4

2021-11-13 20:00 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +	// закрываем модальные окна что б не мешали (иногда даже при старте 1с может появится модальное окно см. макет СкринОшибки_png)
убрать "см. макет СкринОшибки_png" после удаления макета

2021-11-13 20:03 UTC, artbear commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +		ВызватьИсключение КраткоеПредставлениеОшибки(ИнформацияОбОшибке);
этот код уже исправлен, ты юзаешь старую версию.

убери это исправление.

2021-11-13 20:16 UTC, artbear commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +		ЗаписатьИнформациюВЖурналРегистрации("Операция: " + ПолноеИмяФормы);
возможно, метод ВыполнитьЗаписьВЖурналРегистрацииСервер уже не используется и нужно его удалить?

т.к. сейчас дубль записи в ЖР с "Операция: " + ПолноеИмяФормы

2021-11-13 20:40 UTC, LazarenkoA commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +		ВызватьИсключение КраткоеПредставлениеОшибки(ИнформацияОбОшибке);
да это все из-за форматирования

2021-11-14 17:50 UTC, artbear requested changes
Просмотрел большую часть кода, вот комментарии\замечания.

потом остаток досмотрю.

2021-11-14 17:50 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +		ОткрытыеОкна = ПлагинТестКлиенты.ПолучитьСписокОткрытыхОкон(ТестКлиент);
Наверное, нет смысла показывать все окна, а стоит показывать только "новые" окна, возникшие уже после выполнения команды.

т.е. убрать окна, которые есть в ОткрытыеОкнаДо 

этот функционал уже встроен внутрь метода `ПлагинТестКлиенты.ПроверитьНаНовыеМодальныеОкна(ТестКлиент, ОткрытыеОкнаДо);`

Предлагаю выделить экспортный метод плагина - `ПлагинТестКлиенты.НовыеМодальныеОкна(ТестКлиент, ОткрытыеОкнаДо);`

и использовать его вместо полного списка окон

2021-11-14 17:50 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +							|	%1", ОткрытыеОкна));
ОткрытыеОкна - это массив.

внутри СтрШаблон он будет приведен к строке и будет показана только строка "Массив", а не содержимое массива

нужно юзать новый метод `СтроковыеУтилиты.ПредставлениеКоллекции(ОткрытыеОкна);` из соседнего ПР, который вроде бы готов к мержу.

2021-11-14 17:50 UTC, artbear commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +		ОткрытыеОкна = ПлагинТестКлиенты.ПолучитьСписокОткрытыхОкон(ТестКлиент);
ПР с ПредставлениеКоллекции я замержил только что

объедини свою ветку с веткой upstream\develop и заюзай ПредставлениеКоллекции

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		КонтекстЯдра.Отладка(СтрШаблон("ТестКлиентПоУмолчанию: Был использован один из запущенных ранее тест клиентов.
предлагаю оставить и запись в ЖР и выдача отладки.

причина - если отладка выключена, то сообщение никак не зафиксируется, и придется запускать повторно тесты для анализа, что бывает проблематично, да и времени может занять много.

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		Окна,
и здесь приводится Массив к строке, что неверно

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПолучитьСписокОткрытыхОкон(ТестКлиент) Экспорт
есть неформальная рекомендация - не начинать методы с шумящих слов-паразитов

одно из них "Получить"

предлагаю переимеовать метод в ПредставленияОткрытыхОкон(ТестКлиент)

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПопыткаПолучитьПодчиненныеОбъекты(ТестКлиент) Экспорт
Предлагаю переименовать ПодчиненныеОбъекты(ТестКлиент)

по аналогичной причине, что я написал выше

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +//           функция обертка над ПолучитьПодчиненныеОбъекты, выполняется n раз. Попытка обойти ошибку "Ошибка сетевого взаимодействия при вызове"
удали описание-паразит "Функция - Получить подчиненные объекты"

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +//   -
Добавь описание параметра и возвращаемого значения

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПопыткаПолучитьПодчиненныеОбъекты(ТестКлиент) Экспорт
А вообще экспортные методы в этом плагине располагаются в отдельной области, если я не ошибаюсь.

предлагаю перенести метод в эту область.

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +//           функция обертка над ПолучитьПодчиненныеОбъекты, выполняется n раз. Попытка обойти ошибку "Ошибка сетевого взаимодействия при вызове"
в коде функции не видно подтверждения фразы "выполняется n раз"

вызов ПолучитьПодчиненныеОбъекты выполняется всего 1 раз.

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПопыткаПолучитьПодчиненныеОбъекты(ТестКлиент) Экспорт
И зачем этот метод сделан публичным\экспортным?

зачем клиентам плагина иметь доступ к этому методу?
сейчас метод юзается только внутри плагина, снаружи не юзается вроде бы, проверил поиском по бсл-файлам

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		КонецЕсли;
указанный код и комментарий не соответствуют друг другу.

вызов `КонтекстЯдра.ВызватьОшибкуПроверки(Ошибка);` не остановит выполнение других дымовых тестов, т.к. тесты независимы.

фактически ты дважды порождаешь ошибку одного теста, но с немного отличным текстом

я могу ошибиться, но вряд ли )

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
>  			Прервать;
ИМХО зря удалил это условие, т.к. в нем проверяются модальные окна от платформы.

2021-11-14 17:50 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПолучитьОписаниеМодальногоОкна(ОкноПриложения)
и здесь предлагаю переименовать метод в НайтиОписаниеМодальногоОкна

2021-11-14 18:51 UTC, LazarenkoA commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +		ОткрытыеОкна = ПлагинТестКлиенты.ПолучитьСписокОткрытыхОкон(ТестКлиент);
дак это ж просто вывод в лог, логика не завязана на это никакая, ну пусть будут все окна (кроме основного окна), хотя б будет понимание какое окно могло заблокировать

2021-11-14 18:54 UTC, LazarenkoA commented on tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
> +							|	%1", ОткрытыеОкна));
возвращается не массив, строка

2021-11-14 18:54 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		КонтекстЯдра.Отладка(СтрШаблон("ТестКлиентПоУмолчанию: Был использован один из запущенных ранее тест клиентов.
хорошо

2021-11-14 18:55 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		Окна,
не массив

2021-11-14 18:56 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПолучитьСписокОткрытыхОкон(ТестКлиент) Экспорт
ок

2021-11-14 19:09 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПопыткаПолучитьПодчиненныеОбъекты(ТестКлиент) Экспорт
экспортный он по ошибке, видимо копипаст

2021-11-14 19:11 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		КонецЕсли;
закомментил

2021-11-14 19:17 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
>  			Прервать;
Этот код никогда не отрабатывает сейчас т.к. падает на строке 
https://github.com/vanessa-opensource/add/blob/6cac51af023e3a96327a93b5c4ae2ef3b00e7b43/plugins/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/%D0%A2%D0%B5%D1%81%D1%82%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L393
потом в исключение и продолжить, а падает он потому что ПодчиненныеОбъекты это массив, у него нет метода

2021-11-14 19:19 UTC, LazarenkoA commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
>  			Прервать;
да и в целом про какие модальные окна речь? Окно эксепшена, если да, то отрабатывает норм, закрываются они, я проверял

2021-11-14 21:38 UTC, artbear requested changes
еще вопросы есть.

2021-11-14 21:38 UTC, artbear commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +			|Возможно, сеанс тест-клиента заблокирован модальным окном", ПарамНавигационнаяСсылка);
ты удалил мою полезную правку по правильной обработке исключения.

верни, пожалуйста.

2021-11-14 21:38 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Функция ПредставленияОткрытыхОкон(ТестКлиент) Экспорт
публичные методы нужно документировать.

2021-11-14 21:38 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +Процедура ЗакрытьВсеОткрытыеОкнаСУчетомНастроек(ТестКлиент) Экспорт
и этот публичный метод лучше задокументировать

2021-11-14 21:38 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		//ДанныеОкна = СодержимоеОкна(ТекОкно);
комментарии-код без жалости удаляем

2021-11-14 21:38 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		ЗаписатьОшибкуВЖурналеРегистрации(Текст);
неверная обработка исключения - в ЖР нужно писать полное представление ошибки, а не краткое !

2021-11-14 21:38 UTC, artbear commented on plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
> +		//КонецЕсли;
закомментированный код без жалости удаляем

2021-11-15 06:40 UTC, LazarenkoA commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +			|Возможно, сеанс тест-клиента заблокирован модальным окном", ПарамНавигационнаяСсылка);
напиши плиз про какую именно строку речь? Я не вижу что что было удалено
https://github.com/vanessa-opensource/add/blob/6a18eab8f8a7861b4c4b3fa6adc2c8f031b5f4c4/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D1%8B%D0%B9%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D1%8B%D0%B9%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L108

2021-11-15 06:42 UTC, LazarenkoA commented on tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
> +			|Возможно, сеанс тест-клиента заблокирован модальным окном", ПарамНавигационнаяСсылка);
ой не в тот тест посмотрел, ок

2022-01-24 17:00 UTC, LazarenkoA commented
добавил возможность обнаруживать ошибки возникающие в динамическом списке (например когда запрос не корректный), обсуждения тут https://t.me/vanessa_opensource_chat/4288

2022-02-02 18:55 UTC, LazarenkoA commented
реализация https://t.me/vanessa_opensource_chat/4837

2022-02-03 17:37 UTC, LazarenkoA commented
реализация https://t.me/vanessa_opensource_chat/4846 + сделано что б отбор по подсистемам можно было указывать как массив

2022-02-10 07:55 UTC, CrazyHackGUT commented on epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
> +КонецФункции
Точно такой же код есть в модуле формы "УправляемаяФорма", которая, похоже, и передаётся как "КонтекстЯдра" в плагины, т.к. без её редактирования, изменения не взлетают.
https://github.com/vanessa-opensource/add/blob/59e5624de4ed9afd300d1222ab2ed29711756cf8/epf/xddTestRunner/xddTestRunner/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L1895-L1900

2022-02-10 08:53 UTC, LazarenkoA commented on epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
> +КонецФункции
спасибо за ревью, там тоже изменено

2022-04-06 17:11 UTC, artbear commented
Закрываю, т.к. смержен ПР-потомок https://github.com/vanessa-opensource/add/pull/1016

2022-04-06 17:11 UTC, closed without merging