Доработки теста Тесты_ПроверкаПравНаЧтениеОбъектовRLS
silverbulleters/add pull request #945
Opened 2021-11-14 18:24 UTC by LazarenkoA

Добавлена возможность задавать список объектов по шаблону

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-16 18:35 UTC, artbear requested changes
есть предложения по улучшению

2021-11-16 18:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +		СтруктураТеста.Вставить("ИмяПроцедуры", "ТестДолжен_ПроверитьЧтоЕстьПраваНаЧтениеRLS");
Стандарт 1С советует делать функцию-конструктор, в которой возвращать структуру с ключами и значениями по умолчанию.

код создания структуры теста дублируется дважды

2021-11-16 18:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +	Для Каждого ОбъектМетаданных Из Метаданные[СоответствиеОбъектовМетаданных.Получить(ИмяКоллекции)] Цикл
здесь не учитывается, что ИмяКоллекции получается из пользовательских настроек.
и вообще может быть задано пользователем неверно.

в итоге может быть такой путь
- СоответствиеОбъектовМетаданных.Получить(ИмяКоллекции) возвращает Неопределено, если не находит клю
- далее Метаданные[Неопределено] падает с исключением без вменяемой ошибки (

я понимаю, что код унаследован.

просьба - добавь проверку
если возвращается СоответствиеОбъектовМетаданных.Получить(ИмяКоллекции) = Неопределено, тогда нужно выдавать исключение с названием ИмяКоллекции и описание, что настройка получена из файла настроек.

2021-11-16 18:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +		ИмяТеста = СтроковыеУтилиты.ПодставитьПараметрыВСтроку("%1 [%2]", ОбъектМетаданных.ПолноеИмя(), Пояснение);
теперь можно заменить на СтрШаблон

2021-11-16 18:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +					ИмяТеста = СтроковыеУтилиты.ПодставитьПараметрыВСтроку("%1 [%2]",ПолноеИмя, Пояснение);
и тут СтрШаблон можно

2021-11-16 18:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +	Для Каждого ОбъектМетаданных Из Метаданные[СоответствиеОбъектовМетаданных.Получить(ВидМетаданных)] Цикл
и здесь может быть Неопределено и последующее исключение

2021-11-16 18:35 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +	// т.к. на сервере нет возможности использовать КонтекстЯдра.СтрокаСоответствуетШаблону сделано как сделано )
можно использовать КонтекстЯдра.СтрокаСоответствуетШаблону на сервере.

ищи код ВнешниеОбработки.Создать("xddTestRunner") по исходникам 

или в FAQ есть пример

2021-11-17 10:20 UTC, LazarenkoA commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +		СтруктураТеста.Вставить("ИмяПроцедуры", "ТестДолжен_ПроверитьЧтоЕстьПраваНаЧтениеRLS");
а где второй раз?

2021-11-17 17:45 UTC, LazarenkoA commented on tests/smoke/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Тесты_ПроверкаПравНаЧтениеОбъектовRLS/Forms/Форма/Ext/Form/Module.bsl
> +		СтруктураТеста.Вставить("ИмяПроцедуры", "ТестДолжен_ПроверитьЧтоЕстьПраваНаЧтениеRLS");
Одно создание на клиенте, другое на сервере, если сделать функцию-конструктор придется делать на сервере и с клиента не обоснованный вызов сервера будет

2021-11-18 17:58 UTC, merged