для некоторых тестов добавлена возможность исключать по префиксу
silverbulleters/add pull request #948
Opened 2021-11-15 09:29 UTC by LazarenkoA

для тестов
тесты_ПроверкаМакетовСКД
Тесты_ПроверкаПраваИнтерактивногоУдаления
Тесты_ПроверкаПравКУстаревшимОбъектам

добавлена возможность исключать метаданные по префиксу (по аналогии с другими дымовыми)

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-15 13:11 UTC, artbear requested changes
есть ошибка и несколько замечаний

2021-11-15 13:11 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПраваИнтерактивногоУдаления/Тесты_ПроверкаПраваИнтерактивногоУдаления/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат СтрНайти(ВРег(Лев(Имя, ДлинаПрефикса)), ВРег(Префикс)) > 0;
лишнее ВРег(Префикс), т.к. префикс уже в верхнем регистре

2021-11-15 13:11 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат МодульОбъекта().ИмяСодержитПрефикс();
опечатка - нужно передать параметры

2021-11-15 13:11 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПраваИнтерактивногоУдаления/Тесты_ПроверкаПраваИнтерактивногоУдаления/Forms/Форма/Ext/Form/Module.bsl
> +Функция ИмяСодержитПрефикс(Имя, Префикс)
этот метод нужно перенести в плагин СтроковыеУтилиты, иначе много копипаста получается

2021-11-15 13:11 UTC, artbear commented on tests/smoke/Тесты_ПроверкаПраваИнтерактивногоУдаления/Тесты_ПроверкаПраваИнтерактивногоУдаления/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат СтрНайти(ВРег(Лев(Имя, ДлинаПрефикса)), ВРег(Префикс)) > 0;
после переноса в плагин ВРег(Префикс) нужно оставить

2021-11-15 13:27 UTC, LazarenkoA commented on tests/smoke/Тесты_ПроверкаПраваИнтерактивногоУдаления/Тесты_ПроверкаПраваИнтерактивногоУдаления/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат СтрНайти(ВРег(Лев(Имя, ДлинаПрефикса)), ВРег(Префикс)) > 0;
да блин, это копипастом взято с уже закомиченного теста

2021-11-15 13:31 UTC, LazarenkoA commented on tests/smoke/Тесты_ПроверкаПраваИнтерактивногоУдаления/Тесты_ПроверкаПраваИнтерактивногоУдаления/Forms/Форма/Ext/Form/Module.bsl
> +Функция ИмяСодержитПрефикс(Имя, Префикс)
ок, но сделаю только в этих тестах, все рефакторить не буду

2021-11-16 06:48 UTC, LazarenkoA commented on tests/smoke/Тесты_ПроверкаПраваИнтерактивногоУдаления/Тесты_ПроверкаПраваИнтерактивногоУдаления/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат СтрНайти(ВРег(Лев(Имя, ДлинаПрефикса)), ВРег(Префикс)) > 0;
Но в целом это верно что внутри функции приводится в одному регистру, функция не должна полагаться на то, что где-то там будет установлен верхний регистр, это задача данной функции. Стал переносить в плагин и подумал, а зачем она вообще нужна, если есть `СтрНачинаетсяС(ВРег(Имя), ВРег(Префикс))`

2021-11-16 17:59 UTC, artbear requested changes
Замени хардкод имен тестов и я замержу

2021-11-16 17:59 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат "VanessaADD.Дымовые.тесты_ПроверкаМакетовСКД"; // по аналогии с другими тестами
явный хард-код тестов поменять бы на код из чата\из соседних тестов, что обсуждали сегодня

начало в https://t.me/vanessa_opensource_chat/3145

2021-11-16 18:31 UTC, LazarenkoA commented
Мы обсуждали ключ настройки, это события для записи в жр

2021-11-16 18:32 UTC, LazarenkoA commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат "VanessaADD.Дымовые.тесты_ПроверкаМакетовСКД"; // по аналогии с другими тестами
Мы обсуждали ключ настройки, это события для записи в жр

2021-11-16 20:13 UTC, LazarenkoA commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат "VanessaADD.Дымовые.тесты_ПроверкаМакетовСКД"; // по аналогии с другими тестами
Или речь про тесты_ПроверкаМакетовСКД? Если так, ок сделаю

2021-11-17 08:14 UTC, LazarenkoA commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Forms/Форма/Ext/Form/Module.bsl
> +	Возврат "VanessaADD.Дымовые.тесты_ПроверкаМакетовСКД"; // по аналогии с другими тестами
такой момент, тогда придется `ИмяСобытия` сделать &НаСервере, а следовательно и запись в ЖР, что будет не очень  правильным решением, т.к. вызывается она довольно часто

2021-11-18 17:33 UTC, merged