Добавлен тест Тесты_ПроверкаПравНаЧтениеОбъектовRLS2
silverbulleters/add pull request #962
Opened 2021-11-18 18:28 UTC by LazarenkoA

Разница с Тесты_ПроверкаПравНаЧтениеОбъектовRLS в том, что Тесты_ПроверкаПравНаЧтениеОбъектовRLS вообще не позволяет иметь роль на чтение без РЛС (кроме основных), а Тесты_ПроверкаПравНаЧтениеОбъектовRLS2 выявляет те случаи когда на один объект есть 2 роли с РЛС на чтение и просто на чтение (потому что тогда РЛС идет лесом) 

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-18 18:48 UTC, artbear commented
@LazarenkoA Предлагаю назвать тест по-другому, сейчас вообще неинформативно.

желательно из названия дымового теста определять его назначение.

предлагаю 
- Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS
или что-то подобное

2021-11-20 11:05 UTC, artbear commented on tests/smoke/smoke_tests_for_v8std.md
> +([Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS](./Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS))
нужно исправить
> **[2.8.](#тесты) Проверка прав на чтение объектов с RLS - 2** 
([Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS](./Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS))

2021-11-20 11:05 UTC, artbear commented on tests/smoke/smoke_tests_for_v8std.md
> +([Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS](./Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS))
поменять имена

2021-11-20 11:09 UTC, artbear commented on tests/smoke/Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS/Forms/Форма/Ext/Form/Module.bsl
> +	Если Результат <> "" И ПропускатьТест.Пропустить Тогда
А в чем смысл для явно пропускаемых тестов выполнять проверки прав?

ведь проверка прав может выполняться довольно долго при большом количестве прав

2021-11-20 11:10 UTC, artbear requested changes
Есть небольшие замечания

2021-11-20 15:43 UTC, LazarenkoA commented on tests/smoke/Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS/Forms/Форма/Ext/Form/Module.bsl
> +	Если Результат <> "" И ПропускатьТест.Пропустить Тогда
сделано как в Тесты_ПроверкаПравНаЧтениеОбъектовRLS

2021-11-20 15:44 UTC, LazarenkoA commented on tests/smoke/Тесты_ЕстьПравоНаЧтениеПерекрывающееПравоRLS/Forms/Форма/Ext/Form/Module.bsl
> +	Если Результат <> "" И ПропускатьТест.Пропустить Тогда
переделаю

2021-11-22 09:54 UTC, merged