fix: добавлен метод проверки исключения из файла настроек
silverbulleters/add pull request #969
Opened 2021-11-22 14:19 UTC by maximsamokhval

реализация  #964 

сделанные изменения

- в модуль объекта обработки добавлен метод ЕстьВИсключаемойКоллекцииНастроек
- в методы ОбщиеМакеты, ГруппыМакетовМетаданных добавлена проверка на ЕстьВИсключаемойКоллекцииНастроек
- пример исключения взят из [тесты_ПроверкаМакетовСКД](https://github.com/leobrn/ones-smoke-allure/tree/main/src%2Ftests%2F%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2%D0%A1%D0%9A%D0%94)
- после внесения изменений настройки исключений из файла smoke.json начали работать

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-11-22 15:32 UTC, artbear requested changes
Есть небольшое предложение по доработке.

2021-11-22 15:32 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
такой способ поиска найдет только простые совпадения.

а хочется использовать универсальный шаблонный поиск, как в других дымовых тестах.

посмотри использование метода ЕстьВИсключаемойКоллекции

2021-11-22 15:32 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
>  #КонецОбласти
перевод строки, добавь, пожалуйста, в конце файла

2021-11-22 16:20 UTC, maximsamokhval commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
@artbear есть вопрос по этой проверке.
Чтобы получилось как в других дымовых тестах, нужно чтобы из формы дымового теста передавался контекст ядра.
В контекстеЯдра и находится экспортный метод КонтекстЯдра.ЕстьВИсключаемойКоллекции, но есть проблема, что при интерактивном запуске тестов ( в режиме предприятия) КонтекстЯдра в модуле обработки недоступен.

![image](https://user-images.githubusercontent.com/24194977/142896672-aee58b60-9c23-4bc8-bc5e-2ee37d3f3c3b.png)

- Из формы выполняется метод ГруппыМакетовМетаданных()
- В модуле объекта выполняется заполнение макетами без учета исключений, хотя в реквизите Настройки они доступны и заполнены 

![image](https://user-images.githubusercontent.com/24194977/142896996-d1eb0235-b368-4c3d-a51c-15b4437333a1.png)

Вопрос:

- Можно ли получить из модуля объекта теста КонтекстЯдра? или каким образом лучше достучаться до экспортного метода ЕстьВИсключаемойКоллекции?

2021-11-22 19:31 UTC, artbear commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
Посмотри в соседних тестах.
Можно поискать по ВнешниеОбработки.Создать("xddTestRunner

2021-11-22 20:27 UTC, maximsamokhval commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
>  #КонецОбласти
добавил перевод строки

2021-11-22 20:27 UTC, maximsamokhval commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
@artbear реализовал как в других тестах

2021-11-22 20:30 UTC, maximsamokhval commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
>  #КонецОбласти
@artbear добавил инициализацию КонтекстаЯдра и передачу параметров в метод 
КонтекстЯдра.ЕстьВИсключаемойКоллекции. Проверил на своих простых настройках, всё отработало.

2021-11-23 08:18 UTC, leobrn commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
Может сразу добавите для тестов проведение документов и формирование печатных форм ?

2021-11-23 08:20 UTC, maximsamokhval commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
Если реализация текущего теста подходит @artbear , то я могу доработать и эти тесты . Спасибо, что сказали где ещё может быть проблема.

2021-11-23 08:37 UTC, maximsamokhval commented on tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
> +		И Настройки[КлючНастроек].Найти(ЧтоИщем) <> Неопределено
@leobrn @artbear 
Получилась такая реализация.

https://user-images.githubusercontent.com/24194977/142992215-a17d0b6d-91f2-4058-b708-7bf112bf9a5c.mp4

2021-12-02 17:42 UTC, artbear approved these changes

2021-12-02 17:42 UTC, merged