доработка теста тесты_ФормированиеПечатныхФорм
silverbulleters/add pull request #970
Opened 2021-11-25 14:08 UTC by LazarenkoA

Добавил несколько условий, что бы исключались печ. формы по которым не нужно проверки производить

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2021-12-02 17:08 UTC, artbear requested changes
Есть вопрос по исправлению

2021-12-02 17:08 UTC, artbear commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			// предлагаю пропускать такой тест
А почему все-таки не ошибка?
какой бизнес-смысл в печатной форме, у которой высота 0?

2021-12-02 17:48 UTC, LazarenkoA commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			// предлагаю пропускать такой тест
ну потому что в БСП подразумевают что могут быть такие печ. формы и в этом случае пользователь видит такую картину
![image](https://user-images.githubusercontent.com/15386101/144475853-1112e9bc-9add-45fc-bc25-a8ea5f0c3f81.png)

2021-12-02 17:50 UTC, LazarenkoA commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			// предлагаю пропускать такой тест
причин много может быть, например если таб. часть не заполнена в документе, выводится так

2021-12-02 20:02 UTC, LazarenkoA commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			// предлагаю пропускать такой тест
т.е. ошибка это когда возникла исключительная ситуация, не предсказуемая, а когда это предполагаемое поведение, то какая же это ошибка

2021-12-09 11:52 UTC, artbear commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			// предлагаю пропускать такой тест
@LazarenkoA для разработчика в большинстве случаев это исключительная ситуация.
например, выбран неверный документ

и нужно исправить поведение.

предлагаю 
- или оставить как сейчас 
- или сделать спец.параметр в настройках
  -  по умолчанию выключенный
  - тогда и твой, и мой кейс можно будет настроить.

2021-12-09 12:04 UTC, LazarenkoA commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			// предлагаю пропускать такой тест
сделаю параметр

2022-01-02 10:34 UTC, artbear requested changes
Есть небольшие замечания.

Если согласен, исправляй их и я замержу ПР

2022-01-02 10:34 UTC, artbear commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +			Пропустить = Настройки.Свойство("ПропускатьПустыеФормы", ПропускатьПустыеФормы) И ПропускатьПустыеФормы;
Вычисление этой настройки происходит в цикле.

предлагаю перенести выше, туда, где задается переменная ПропускатьПустыеФормы

2022-01-02 10:34 UTC, artbear commented on tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
> +	Результат.Вставить("ПропускатьПустыеФормы", Истина);
по умолчанию все-таки ПропускатьПустыеФормы должно быть Ложь, а не Истина )

2022-04-06 17:15 UTC, merged