Доработка теста тесты_ПроведениеДокументов
silverbulleters/add pull request #971
Opened 2021-11-26 18:13 UTC by LazarenkoA

Заменена функция `СтрСоединить_` на встроенную, т.к. `СтрСоединить_` работала не корректно

![image](https://user-images.githubusercontent.com/15386101/143618230-88b7aa66-df20-4786-8d8d-b25ca28afae3.png)
![image](https://user-images.githubusercontent.com/15386101/143618243-107bcf99-37b8-4214-813e-19116a9ea18f.png)
------------------

в настройки теста добавлена возможность сверять строки без учета порядка, сейчас могут быть такие ситуации

![image](https://user-images.githubusercontent.com/15386101/143618400-987c853f-54c1-4853-a489-c2b88ad7355c.png)
------------------

Добавлена возможность исключать конкретные поля при проверки движений, т.к. могут быть такие ситуации
![image](https://user-images.githubusercontent.com/15386101/143618581-c3dde44b-ceab-462f-86db-0485befe6296.png)

------------------

добавлена возможность устанавливать отбор по полям документов 

@vanessa-opensource/Collaborators - просьба прокомментировать и проверить

2022-01-02 10:47 UTC, artbear requested changes
Есть небольшие замечания.

2022-01-02 10:47 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +	КонецЕсли;
в чате обсуждали, что не нужно делать доп.отмену проведения, и ты с этим согласился.

предлагаю эти строки убрать.

2022-01-02 10:47 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +			ИсключенияПолей = Вычислить(СтрШаблон("Настройки.ИсключенияИзПроверкиДвижений.%1", ИмяМетаданных));
после этой строки предлагаю добавить проверку типа переменной ИсключенияПолей , убедиться, что это Массив.

т.к. эта переменная фактически задается пользователем в json и может быть неверного значения, или вообще не быть задана.
```bsl
КлючПараметра = СтрШаблон("Настройки.ИсключенияИзПроверкиДвижений.%1", ИмяМетаданных);
ИсключенияПолей = Вычислить(КлючПараметра);
ХХХ.ПроверитьТип(ИсключенияПолей, "Массив", "Ожидали, что в json-файле настройки для параметра указан массив, а это не так. Ключ параметра - " + КлючПараметра );
```

2022-01-02 10:51 UTC, LazarenkoA commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +	КонецЕсли;
Просто так убитюрать нельзя т.к. проблема присутствует, вот сообщение из чата где я предлагаю альтернативу 
https://t.me/vanessa_opensource_chat/3791
Следующее сообщение демонстрирует саму проблему

2022-01-02 11:13 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +	КонецЕсли;
Лучше, конечно, очистить

![image](https://user-images.githubusercontent.com/2920817/147873970-59ae7061-9389-4476-b32c-83ede6de720c.png)

только отдельной строкой-вызовом, а не внутри метода ПолучитьДвиженияДокумента

добавить вызов Очистить сразу после вызова этого метода

2022-01-02 11:20 UTC, LazarenkoA commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +	КонецЕсли;
А может параметр лучше сделать, типа очищать набор записей?

2022-04-06 18:42 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +	КонецЕсли;
Есть тест-пример, подтверждающий необходимость очистки https://t.me/vanessa_opensource_chat/6294

2022-04-09 11:11 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +	КонецЕсли;
согласен с очисткой.

вопрос решен https://t.me/vanessa_opensource_chat/6391

2022-04-09 11:19 UTC, artbear requested changes
Небольшое дополнение.

2022-04-09 11:19 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +			ИсключенияПолей = Вычислить(СтрШаблон("Настройки.ИсключенияИзПроверкиДвижений.%1", ИмяМетаданных));
Если в настройке ИсключенияИзПроверкиДвижений не будет имени метаданных, 
- тогда эта строка кода с Вычислить упадет с исключением.
- тест также упадет с непонятным сообщением

@LazarenkoA верно?

и тогда лучше проверить наличие этого свойства штатным 
```bsl
ИсключенияПолей = Неопределено;
Если Настройки.ИсключенияИзПроверкиДвижений.Свойство(ИмяМетаданных, ИсключенияПолей)
И ТипЗнч(ИсключенияПолей) = Тип("Массив") Тогда
```

2022-04-12 07:40 UTC, LazarenkoA commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +			ИсключенияПолей = Вычислить(СтрШаблон("Настройки.ИсключенияИзПроверкиДвижений.%1", ИмяМетаданных));
так у меня есть данное условие
https://github.com/LazarenkoA/add/blob/c6204e792ed971b28e1ef7239c66ef0fc09c595b/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2/Ext/ObjectModule.bsl#L81

2022-04-12 07:50 UTC, LazarenkoA commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +			ИсключенияПолей = Вычислить(СтрШаблон("Настройки.ИсключенияИзПроверкиДвижений.%1", ИмяМетаданных));
не упадет т.к. выше есть условие
```
Если ПлагинНастроек.ЕстьНастройка(ИмяМетаданных, Настройки.ИсключенияИзПроверкиДвижений) Тогда
```

2022-04-12 10:35 UTC, artbear commented on tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
> +			ИсключенияПолей = Вычислить(СтрШаблон("Настройки.ИсключенияИзПроверкиДвижений.%1", ИмяМетаданных));
я ошибся, закрываю этот вопрос

2022-04-12 10:43 UTC, merged